const SAVE_PROFILE_URL = 'saveProfile'
const SAVE_ALL_PROFILES_URL = 'saveProfiles'
const IMPORT_URL = 'import'
const ATTRIBUTES_GROUP_AUTOCOMPLETE_URL = 'attributesGroupAutocomplete'

const DEFAULT_PROFILE_NAME = 'default'

export {
  SAVE_PROFILE_URL,
  SAVE_ALL_PROFILES_URL,
  IMPORT_URL,
  ATTRIBUTES_GROUP_AUTOCOMPLETE_URL,
  DEFAULT_PROFILE_NAME
}
